### ISSUE TITLE
CPU charts blank on revision 28 with Grafana 9.2.2

### ISSUE THREAD

**Issue by bleetube** [rfmoz/grafana-dashboards#105] opened 2022-10-25 23:36 UTC
CPU graphs seem borked on rev28 for me.  Both of my "CPU Basic" and "CPU" graphs are blank on revision 28 with Grafana 9.2.2. If I downgrade either Grafana to 9.1.0, or the dashboard to revision 27, the charts display data again. I think this is due to some new issue and not related to the old `$__rate_interval` problems. I've tried replacing with `s/$__rate_interval/5m/` and they're still blank. Otherwise all other charts are showing data as expected. Since I'm working on an ansible playbook, I tried reproducing the issue on a couple different versions and two Ubuntu releases (different Ubuntu, Prometheus, and node_exporter versions made no difference).

| Grafana  | node-exporter-full | CPU charts |
| ------------- | ------------- | ------------- |
| 9.1.0  | rev27  | Perfect |
| 9.2.2  | rev27  | Perfect |
| 9.1.0  | rev28  | [weird flat line](https://user-images.githubusercontent.com/77934086/197900788-a326d8dd-3166-4032-85b6-43a6bcae662e.jpg) |
| 9.2.2  | rev28  | blank  |

**Comment by courtland** [comment] 2022-10-26 16:18
I noticed this as well yesterday and thought I was losing my mind / had broken something strange. Turns out I had upgraded from Grafana 9.2.1 to 9.2.2. Downgrading to 9.2.1 fixed the problem. Seems like a regression in the 9.2.2 release?

**Comment by xelatirdan** [comment] 2022-10-31 09:05
https://github.com/grafana/grafana/issues/57690#issuecomment-1296787752

**Comment by mennozon** [comment] 2022-10-31 12:26
Thanks @xelatirdan, now it shows the graph again.

I did notice the graph looks a little weird because it isn't scaling to max 100 (max now is 100 * nr cpus), a workaround for this is to change max to 'auto' instead of the default 100, the graph looks okay again but values are still multiplied with the number of CPU's.

**Comment by Z10N0110** [comment] 2022-11-03 09:00
After doing some research on the dashboard, I made a pull request to fix this. Tested on grafana 9.2.3. Working perfectly.

#109

**Comment by IanSmith123** [comment] 2022-11-03 13:17
> Thanks @xelatirdan, now it shows the graph again.
> 
> I did notice the graph looks a little weird because it isn't scaling to max 100 (max now is 100 * nr cpus), a workaround for this is to change max to 'auto' instead of the default 100, the graph looks okay again but values are still multiplied with the number of CPU's.

It works for me!  Thank you very much.

**Comment by xelatirdan** [comment] 2022-11-25 14:26
@Z10N0110 I've tested on grafana 9.2.6 and it works fine for me.

**Comment by courtland** [comment] 2022-11-27 22:00
The change to using irate in 6bcaee1194cc9b578d1753a0fc15a24b52d8fc44 fixed the issue for me as well. I believe the bug in Grafana itself prior to that change still exists.

**Comment by guidodobboletta** [comment] 2023-01-18 19:45
This is still an issue for me using the latest dashboard on Github and Grafana 9.3.2

![image](https://user-images.githubusercontent.com/24704808/213279404-5745a2c7-3fb5-4b70-94d3-ee53490f795c.png)

**Comment by guidodobboletta** [comment] 2023-01-19 19:22
By changing the time range from 24 hours to 2 days they now show up for some reason

![image](https://user-images.githubusercontent.com/24704808/213540095-6cd50349-4f95-45ef-8f3a-a43841674205.png)

**Comment by teamsmiley** [comment] 2023-06-06 12:56
hi I still having this issue with Grafana 9.4.3

The funny thing is above 12 hours. I can see CPU graph

<img width="1944" alt="image" src="https://github.com/rfmoz/grafana-dashboards/assets/4934139/6f900dcc-d2f1-414d-8a75-19bc52c9465a">

but I change it to under 12 hours I got this 

<img width="1977" alt="image" src="https://github.com/rfmoz/grafana-dashboards/assets/4934139/8c5e8627-ffd3-472a-ba2c-85cfdc2378e1">

I used use node_exporter 1.2.0
I upgrade to node_exporter 1.6.0 but still not showing a graph under 12 hours

any idea?

**Comment by teamsmiley** [comment] 2023-06-06 15:37
i change my prometheus config, then it works now 

```
#scrape_interval: 1m
scrape_interval: 30s
```

**Comment by rfmoz** [comment] 2023-08-26 13:48
This was fixed on https://github.com/grafana/grafana/issues/57690#issuecomment-1329324668

**Closed by rfmoz** 2023-08-26 13:48 UTC
