### ISSUE TITLE
CPU Usage & Network Traffic Basic not reflecting over Grafana

### ISSUE THREAD

**Issue by MD-star-cloud33** [rfmoz/grafana-dashboards#149] opened 2023-11-22 09:55 UTC
Node Exporter Running Over An Instance-1, prometheus & Grafana Running on Instance 2.
But Grafana Dashboard not reflecting CPU Usage & Network Traffic Basic info.

<img width="515" alt="Screenshot 2023-11-22 at 3 17 31 PM" src="https://github.com/rfmoz/grafana-dashboards/assets/64517547/c1306311-07d2-47cc-b044-91618c664daf">

<img width="1491" alt="image" src="https://github.com/rfmoz/grafana-dashboards/assets/64517547/a775f859-a214-4f5b-a96c-40c09f772023">

<img width="1470" alt="image" src="https://github.com/rfmoz/grafana-dashboards/assets/64517547/27b18a00-3730-4504-8210-6f1e3e666b62">

**Comment by byteborg** [comment] 2023-12-01 18:12
Same here, node_exporter running dockerized under linux.
node_cpu_* and friends are present and are visible in prometheus native UI.

**Comment by byteborg** [comment] 2023-12-01 18:17
This is a DUP to #137 
The resolution is adjusting the scrape interval in the data source, corresponding to the Prometheus configuration.

**Comment by rfmoz** [comment] 2023-12-09 12:26
Duplicate of #137

**Closed by rfmoz** 2023-12-09 12:26 UTC
