### ISSUE TITLE
Dashboard View Doesn't Update When Datasource Changed

### ISSUE THREAD

**Issue by desebjohnston** [rfmoz/grafana-dashboards#139] opened 2023-06-22 16:24 UTC
This is probably a fundamental misunderstanding of how this dashboard works. I have multiple prometheus datasources on separate hosts on port 9090 each with their own node_exporter that is targeted by each hosts own prometheus instance scraping via localhost:9100. When I change the datasource in the dashboard none of the metrics change, but the host still targets localhost:9100. I'm guessing the metrics are only being collected on the localhost:9100 of the server running the grafana instance. If I update the prometheus targets for node_exporter to include multiple targets wouldn't every host scrape every other host in the network?

**Comment by calestyo** [comment] 2023-11-24 04:35
I have the same problem. The reason seems to be that after importing, Grafana somehow rewrites the dashboard’s `DS_PROMETHEUS` variable to some fixed data source,... and it also shows the variable then to be unused (under Settings/Variables).

**Comment by calestyo** [comment] 2023-11-24 04:40
Oh and this is a duplicate of #51.

**Closed** 2023-12-09 12:09 UTC
